SUFFIXES = [
    'ltd',
    'inc',
    'plc',
    'limited',
    'corp',
    'a',
    'npv',
    'wt',
    'trust',
    'group',
    'adr',
    'holdings',
    'holding',
    "hldg",
    "hldgs",
    'corporation',
    'spdr',
    'usd',
    'icav',
    'debs',
    'ii',
    'limited',
    'units',
    'b',
    'cl',
    'cl.a',
    'cl.b',
    'cl.c',
    'cp',
    'inc',
    'etn',
    'lp',
    'i',
    'nl',
    'li',
    's.a',
    'c',
    'n.v',
    'wts',
    'c',
    'ag',
    'in',
    'nl',
    'ads',
    'ld',
    'sv',
    'pl',
    'llc',
    'cs',
    'ord',
    'iii',
    'unit',
    'sys',
    'incorporated',
    'co',
    'ft',
    'intl'
]
SUFFIXES.extend([
    f"{suffix}."
    for suffix in SUFFIXES
])
SUFFIXES.extend([
    suffix.replace(".", "")
    for suffix in SUFFIXES
])
SUFFIXES = sorted(list(set(SUFFIXES)))

MODIFIERS = [
    'resources',
    'acquisition',
    'company',
    'international',
    'energy',
    'mining',
    'capital',
    'technologies',
    'minerals',
    'metals',
    'therapeutics',
    'investment',
    'financial',
    'solutions',
    'technology',
    'pharmaceuticals',
    'bancorp',
    'services',
    'bank',
    'partners',
    'systems',
    'pharma',
    'exploration',
    'industries',
    'global',
    'banking',
    'investments',
    'mines',
    'health',
    'petroleum',
    "properties",
    'property',
    "tech",
    'management',
    'entertainment',
    "development",
    'media',
    'ventures',
    'medical',
    'healthcare',
    'insurance',
    "enterprises",
    "sciences",
    "communications",
    'realty',
    "brands",
    "biosciences",
    "power",
    "education",
    "finance",
    "bio",
    "leaders",
    "products",
    "and",
    "&"
]

SYNONYMS = [
    [" ltd ", " limited "],
    [" inc ", " incorporated "],
    [" corp ", " corporation "],
    [" hldg ", " holding "],
    [" hldgs ", " holdings "],
    [" co ", " company "],
    [" pharma ", " pharmaceuticals "],
]

SAFE_SUFF_SINGLES = [
    'blackberry',
    'bombardier',
    'asana',
    'caterpillar',
    'chevron',
    'footlocker',
    'nike',
    'oracle',
    'snowflake',
    'square',
    'rogers',
    'target',
    'twitter',
    'visa',
    'xerox',
    'yelp',
    'puma',
    'acer',
    'burberry',
    'apple',
    'bumble',
    'fox',
    'alphabet',
    'tesla',
    'upstart',
    'hp',
    'jd',
    '3m',
]

SAFE_MOD_SINGLES = [
    "hermes",
    "acer",
    "adobe",
    "bentley",
    "cisco",
    "dell",
    "gilead",
    "kala",
    "lloyds",
    "marathon",
    "micron",
    "pretium",
    "rogers",
    "slack",
    "arbor"
]

SAFE_TWO_GRAMS = [
    'general electric',
    'general motors',
    'western union',
    'american express',
    'ford motor',
    'good works',
    'waste management'
]

MANUAL_OVERRIDES = [
    'renewable energy',
    'silicon sensor',
    'retail estates',
    'new homes',
    'apartment investment',
    'cohen',
    'deere',
    'u and',
]

TARGET_FALSE_PRES = [
    "price",
    "new",
    "upside",
    "downside",
    "raises",
    "lowers",
    "cuts",
    "inflation",
    "yield",
    "acquisition",
    "exploration",
    "m&a",
    "to",
    "slashes",
    "drops",
    "short",
    "long",
    "growth",
    "opec",
    "vaccine",
    "'s",
    "spac"
]
TARGET_FALSE_POSTS = [
    "price",
    "of",
    "by",
    "at",
    "raised",
    "lowered",
    "lifted",
    "dropped",
    "slashed",
    "cut",
]